//
// Created by shachar Meir on 09/01/2020.
//

#ifndef FLIGHT_SIMULATOR__BINDDIRECTION_H_
#define FLIGHT_SIMULATOR__BINDDIRECTION_H_
enum BindDirection{
  LEFT,RIGHT
};
#endif //FLIGHT_SIMULATOR__BINDDIRECTION_H_
